name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/app-backend:${{ github.sha }} \
            ./backend
      - name: Push Image
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/app-backend:${{ github.sha }}
  update-gitops:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: dangph12/gitops-demo
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops-demo
      - name: Debug Directory Structure
        run: |
          echo "Root directory contents:"
          ls -la
          echo "---"
          echo "GitOps repository contents:"
          ls -la gitops-demo/
          echo "---"
          echo "Apps directory contents:"
          ls -la gitops-demo/apps/gitops-app/
      - name: Update Image Tag
        run: |
          sed -i "s|app-backend:.*|app-backend:${{ github.sha }}|" gitops-demo/apps/gitops-app/deployment.yml

      - name: Commit Changes
        run: |
            cd gitops-demo
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            git add apps/gitops-app/deployment.yml

            git commit -m "update app-backend image to ${{ github.sha }}" || exit 0

            git remote set-url origin https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/dangph12/gitops-demo.git

            git push
